"""Closed M3 candidate-to-terminal semantic-ingestion contracts.

This package deliberately owns candidate validation and non-promoting terminal
evidence.  It does not own graph arbitration or a provider-specific model.
"""

from memorii.core.semantic_ingestion.authorization import (
    M3AuthorizationAuthorityError,
    M3AuthorizationAuthorityRepository,
    M3AuthorizationTransitionVerifier,
    M3VerifiedAuthorizationTransition,
    VerifiedM3AuthorizationControlPlane,
)
from memorii.core.semantic_ingestion.capability import (
    AuthorizedSemanticIngestionRuntime,
    HostSemanticIngestionRuntimeBuilder,
    SemanticIngestionRuntimeAuthorization,
    build_authorized_local_semantic_runtime,
)
from memorii.core.semantic_ingestion.carriers import (
    AcceptedTemporalEvidence,
    ActionRevision,
    ClaimAssertion,
    IdentityLineageRecord,
    TemporalTransitionRecord,
)
from memorii.core.semantic_ingestion.contracts import (
    AuthenticatedDocumentTimeReference,
    AuthenticatedEventTimeReference,
    AuthenticatedSourceIntervalEvidence,
    AuthorizationStageSnapshot,
    IndependentSourceAnalysis,
    M3ArtifactClosure,
    M3EventBatch,
    M3ExecutionLineage,
    M3ExecutionRetryPlan,
    M3GraphDelta,
    M3GroupResult,
    M3ObservationDelta,
    M3RecoveryAuthorityBinding,
    SemanticArbitrationPolicyBundle,
    SemanticContractCodecError,
    SemanticTerminalBindingSet,
    SourceTemporalEvidenceSet,
    TemporalReferenceEvidence,
    decode_semantic_contract,
    encode_semantic_contract,
)
from memorii.core.semantic_ingestion.egress import (
    EgressPolicyError,
    InMemoryEgressPolicyRepository,
    JsonlEgressPolicyRepository,
    ProviderEgressBinding,
    ProviderEgressDecision,
    SignedEgressPolicyCommand,
)
from memorii.core.semantic_ingestion.local_analyzer import (
    LocalSemanticProposalProducer,
    ProductionLocalSemanticAnalyzer,
)
from memorii.core.semantic_ingestion.persistence import M3TerminalPersistenceService
from memorii.core.semantic_ingestion.pipeline import (
    AnalyzerRoleInterpretation,
    CandidateTransportError,
    OperationTemporalAttachmentBinding,
    OperationTemporalDecisionBinding,
    ParserConsensusAssessment,
    SemanticCandidate,
    SemanticIngestionPipeline,
    SemanticPipelinePolicy,
    SemanticPipelinePolicyProvider,
    SemanticTerminalOutcome,
    SourceAuthority,
    SourceLocalIdentityEvidence,
    SourceSpan,
    TemporalEvidenceCandidate,
    TemporalEvidenceDecisionClosure,
    TemporalEvidenceResolver,
    TemporalPolicySnapshot,
    TimeInterval,
    TrustPolicySnapshot,
)
from memorii.core.semantic_ingestion.prompt_authority import (
    RegisteredSemanticPromptBinding,
    SemanticPromptAuthority,
)

__all__ = [
    "CandidateTransportError",
    "M3AuthorizationAuthorityError",
    "M3AuthorizationAuthorityRepository",
    "M3AuthorizationTransitionVerifier",
    "M3VerifiedAuthorizationTransition",
    "VerifiedM3AuthorizationControlPlane",
    "AuthorizedSemanticIngestionRuntime",
    "build_authorized_local_semantic_runtime",
    "AuthenticatedSourceIntervalEvidence",
    "AuthenticatedDocumentTimeReference",
    "AuthenticatedEventTimeReference",
    "AuthorizationStageSnapshot",
    "IndependentSourceAnalysis",
    "AcceptedTemporalEvidence",
    "ActionRevision",
    "ClaimAssertion",
    "IdentityLineageRecord",
    "HostSemanticIngestionRuntimeBuilder",
    "M3ArtifactClosure",
    "M3ExecutionRetryPlan",
    "M3EventBatch",
    "M3ExecutionLineage",
    "M3GraphDelta",
    "M3GroupResult",
    "M3ObservationDelta",
    "M3RecoveryAuthorityBinding",
    "M3TerminalPersistenceService",
    "LocalSemanticProposalProducer",
    "ProductionLocalSemanticAnalyzer",
    "AnalyzerRoleInterpretation",
    "OperationTemporalAttachmentBinding",
    "OperationTemporalDecisionBinding",
    "ParserConsensusAssessment",
    "SemanticCandidate",
    "SemanticIngestionPipeline",
    "SemanticPipelinePolicy",
    "SemanticPipelinePolicyProvider",
    "SemanticContractCodecError",
    "SemanticIngestionRuntimeAuthorization",
    "SemanticArbitrationPolicyBundle",
    "SemanticTerminalBindingSet",
    "SemanticTerminalOutcome",
    "SourceAuthority",
    "SourceLocalIdentityEvidence",
    "SourceSpan",
    "SourceTemporalEvidenceSet",
    "TemporalEvidenceCandidate",
    "TemporalEvidenceDecisionClosure",
    "TemporalEvidenceResolver",
    "TemporalReferenceEvidence",
    "TemporalPolicySnapshot",
    "TimeInterval",
    "TemporalTransitionRecord",
    "TrustPolicySnapshot",
    "EgressPolicyError",
    "InMemoryEgressPolicyRepository",
    "JsonlEgressPolicyRepository",
    "ProviderEgressBinding",
    "ProviderEgressDecision",
    "RegisteredSemanticPromptBinding",
    "SemanticPromptAuthority",
    "SignedEgressPolicyCommand",
    "decode_semantic_contract",
    "encode_semantic_contract",
]
