"""Minimal model integration contracts for solver decisions."""

from typing import Protocol

from pydantic import BaseModel, ConfigDict, Field

from memorii.core.solver.update_engine import SolverDecisionOutput


class SolverContextItem(BaseModel):
    """Compact context record passed into model providers."""

    memory_id: str
    memory_domain: str
    content: dict[str, object] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class SolverModelInput(BaseModel):
    """Structured model input generated by runtime."""

    task_id: str
    execution_node_id: str
    solver_run_id: str
    observation_event_id: str
    observation_text: str
    context_items: list[SolverContextItem] = Field(default_factory=list)
    available_evidence_ids: list[str] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


class SolverModelProvider(Protocol):
    """Pluggable provider contract used by runtime solver integration."""

    def generate_decision(self, model_input: SolverModelInput) -> SolverDecisionOutput:
        """Return structured solver decision output."""


class StaticSolverModelProvider:
    """Deterministic provider for tests and simple harness integrations."""

    def __init__(self, fixed_output: SolverDecisionOutput) -> None:
        self._fixed_output = fixed_output

    def generate_decision(self, model_input: SolverModelInput) -> SolverDecisionOutput:
        return self._fixed_output


class OpenAIStyleSolverModelProvider:
    """Minimal OpenAI-style provider adapter.

    This keeps the contract simple and dependency-free by accepting an injected
    client callable that returns a dict-compatible structured payload.
    """

    def __init__(self, completion_client: "OpenAIStyleCompletionClient") -> None:
        self._client = completion_client

    def generate_decision(self, model_input: SolverModelInput) -> SolverDecisionOutput:
        raw_payload = self._client.create_completion(model_input)
        return SolverDecisionOutput.model_validate(raw_payload)


class OpenAIStyleCompletionClient(Protocol):
    """Protocol for OpenAI-style completion clients used by provider wrapper."""

    def create_completion(self, model_input: SolverModelInput) -> dict[str, object]:
        """Generate a structured response payload for SolverDecisionOutput."""
