"""Grounded answering primitives."""

from memorii.core.grounding.models import (
    AlternativeAnswerCheck,
    AnswerRequirement,
    AnswerRequirementType,
    AnswerVerificationContext,
    AnswerVerificationDecision,
    CandidateAnswerConsidered,
    CandidateRequirementCoverage,
    EvidenceCandidate,
    EvidenceSelectionContext,
    EvidenceSelectionDecision,
    GroundedAnswerContext,
    GroundedAnswerDecision,
    GroundedAnswerPipelineResult,
    ProofCitationRole,
    ProofStep,
    ProofStepCitation,
    QuestionConstraintCoverage,
)
from memorii.core.grounding.pipeline import (
    GroundedAnswerPipeline,
    fake_llm_result_for_answer_verification,
    fake_llm_result_for_evidence_selection,
    fake_llm_result_for_grounded_answer,
)

__all__ = [
    "AlternativeAnswerCheck",
    "AnswerRequirement",
    "AnswerRequirementType",
    "AnswerVerificationContext",
    "AnswerVerificationDecision",
    "CandidateAnswerConsidered",
    "CandidateRequirementCoverage",
    "EvidenceCandidate",
    "EvidenceSelectionContext",
    "EvidenceSelectionDecision",
    "GroundedAnswerContext",
    "GroundedAnswerDecision",
    "GroundedAnswerPipeline",
    "GroundedAnswerPipelineResult",
    "ProofCitationRole",
    "ProofStep",
    "ProofStepCitation",
    "QuestionConstraintCoverage",
    "fake_llm_result_for_answer_verification",
    "fake_llm_result_for_evidence_selection",
    "fake_llm_result_for_grounded_answer",
]
